{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"transaction_data_transaction_data1\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.141.1558.0 (25.03)+75b5f06a991f8f8a8a4d6b6fcd0f66e1ec2d6fdc"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "aedef54c-d87f-496d-b5a2-7aec48216d70",
        "fromColumn": "Transaction Date",
        "fromTable": "transaction_data_transaction_data1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bfdafc33-0205-4ce5-8e87-fb3108f1f953"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "transaction_data_transaction_data1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "062e2478-cb3a-4dbf-8cc8-d6a3b6563fb7",
            "sourceColumn": "Channel",
            "summarizeBy": "none"
          },
          {
            "name": "Flag Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1bc78ea3-350a-4571-bdce-3e2a5f37a7d5",
            "sourceColumn": "Flag Reason",
            "summarizeBy": "none"
          },
          {
            "name": "Is Flagged?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44f7ffbb-c901-419c-a2d5-4e61045fa858",
            "sourceColumn": "Is Flagged?",
            "summarizeBy": "none"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "562496b9-030c-4628-a27e-f4f48131c474",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          },
          {
            "name": "Months",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcd6982a-681a-420c-9b96-2fe30d194a64",
            "sourceColumn": "Months",
            "summarizeBy": "none"
          },
          {
            "name": "Response Message",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ba29ce3-4aa0-424d-946b-7a8125c837b7",
            "sourceColumn": "Response Message",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a73d5e6b-9869-4705-8154-485a94e07af5",
            "sourceColumn": "Transaction Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bfdafc33-0205-4ce5-8e87-fb3108f1f953"
                },
                "isDefault": true,
                "relationship": "aedef54c-d87f-496d-b5a2-7aec48216d70"
              }
            ]
          },
          {
            "name": "Transaction Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db5a97d0-e568-4071-9085-7175f614397f",
            "sourceColumn": "Transaction Status",
            "summarizeBy": "none"
          },
          {
            "name": "y/m",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69970e9d-0d9e-4a81-a3b7-25a8b58f71b0",
            "sourceColumn": "y/m",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "16ae0372-20b1-4cee-a928-8e6e722a2b52",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "% MoM success rate (+)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccd8b8c5-122c-4e5a-a5a8-46407bbc320c",
            "sourceColumn": "% MoM success rate (+)",
            "summarizeBy": "none"
          },
          {
            "name": "% MoM success rate (-)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe897378-4964-423e-b1bf-70c40f2819c6",
            "sourceColumn": "% MoM success rate (-)",
            "summarizeBy": "none"
          },
          {
            "name": "% MoM Value (+)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61662eca-28dc-4a93-9492-8990ae53fb88",
            "sourceColumn": "% MoM Value (+)",
            "summarizeBy": "none"
          },
          {
            "name": "% MoM Value (-)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03d810a6-e59a-4ac9-9eae-254bdcc57e2a",
            "sourceColumn": "% MoM Value (-)",
            "summarizeBy": "none"
          },
          {
            "name": "% MoM Volume (+)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05b3e660-9aa7-4a0a-8aa7-73144074e4a5",
            "sourceColumn": "% MoM Volume (+)",
            "summarizeBy": "none"
          },
          {
            "name": "% MoM Volume (-)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3cfc9487-d8f9-4057-a75f-7376a28f07c5",
            "sourceColumn": "% MoM Volume (-)",
            "summarizeBy": "none"
          },
          {
            "name": "% YoY success rate (+)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3fabc0d-5d46-49bc-a7b8-b91dd91fc3f1",
            "sourceColumn": "% YoY success rate (+)",
            "summarizeBy": "none"
          },
          {
            "name": "% YoY success rate (-)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "decf20b2-7018-49c5-b319-8faf14bfb696",
            "sourceColumn": "% YoY success rate (-)",
            "summarizeBy": "none"
          },
          {
            "name": "% YoY Value (+)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "240eab6b-60a5-447d-b097-565d4f2d3fbd",
            "sourceColumn": "% YoY Value (+)",
            "summarizeBy": "none"
          },
          {
            "name": "% YoY Value (-)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f9be390-7bb3-4dee-b8af-3ffeadf2a4a5",
            "sourceColumn": "% YoY Value (-)",
            "summarizeBy": "none"
          },
          {
            "name": "% YoY Volume (+)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ca0ff30-cb4e-4e5b-9173-2085066d3cb8",
            "sourceColumn": "% YoY Volume (+)",
            "summarizeBy": "none"
          },
          {
            "name": "% YoY Volume (-)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "978f0f73-08f4-4833-bd01-b17b309c6a60",
            "sourceColumn": "% YoY Volume (-)",
            "summarizeBy": "none"
          },
          {
            "name": "CM Failure Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68f701de-f4fa-470b-a3e6-6c30f1d208ed",
            "sourceColumn": "CM Failure Rate",
            "summarizeBy": "none"
          },
          {
            "name": "CM Flag Transactions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec470dd4-bb6e-4076-b67b-b90cb7725fbd",
            "sourceColumn": "CM Flag Transactions",
            "summarizeBy": "none"
          },
          {
            "name": "CM Success Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51c46716-5d7e-4e5a-90be-acf154867126",
            "sourceColumn": "CM Success Rate",
            "summarizeBy": "none"
          },
          {
            "name": "CM Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9912fb8c-808b-4b3e-82b0-f9628309ba44",
            "sourceColumn": "CM Value",
            "summarizeBy": "none"
          },
          {
            "name": "CM Value formatted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc11d90d-f77f-4872-a822-0889ce0141ce",
            "sourceColumn": "CM Value formatted",
            "summarizeBy": "none"
          },
          {
            "name": "CM Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "394baa73-df10-4735-a031-5b90b0b6d95d",
            "sourceColumn": "CM Volume",
            "summarizeBy": "none"
          },
          {
            "name": "CY Decline Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b28e22dc-2c62-499f-9692-a5c5c92a877f",
            "sourceColumn": "CY Decline Rate",
            "summarizeBy": "none"
          },
          {
            "name": "CY Success Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a02e01cd-1e55-4579-ac55-f9e1e7fd47ec",
            "sourceColumn": "CY Success Rate",
            "summarizeBy": "none"
          },
          {
            "name": "CY Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12aacc28-b4c7-4a06-9bd9-7ca1590fabef",
            "sourceColumn": "CY Value",
            "summarizeBy": "none"
          },
          {
            "name": "CY Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e434d0d-21df-4176-ae52-7c9b6f89f846",
            "sourceColumn": "CY Volume",
            "summarizeBy": "none"
          },
          {
            "name": "PM Failure Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a69bf881-93f8-4e69-a7a1-b7eb6355ef80",
            "sourceColumn": "PM Failure Rate",
            "summarizeBy": "none"
          },
          {
            "name": "PM Success Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "972ec172-ff7c-476f-a88d-dfde43264f7d",
            "sourceColumn": "PM Success Rate",
            "summarizeBy": "none"
          },
          {
            "name": "PM Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "241caa0b-b6da-4b2c-83f2-a09ecdfb8c52",
            "sourceColumn": "PM Value",
            "summarizeBy": "none"
          },
          {
            "name": "PM Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4e5db91-7aaa-403a-bac4-7fc2922f1e62",
            "sourceColumn": "PM Volume",
            "summarizeBy": "none"
          },
          {
            "name": "prev year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5bbe5193-9877-423f-bdda-91bb76e47074",
            "sourceColumn": "prev year",
            "summarizeBy": "sum"
          },
          {
            "name": "PY Success Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dd47ebfc-938a-49f5-94af-c55c693ebfa6",
            "sourceColumn": "PY Success Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "PY Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "858f8778-c8bc-4c12-9d99-13fc8f444ca5",
            "sourceColumn": "PY Value",
            "summarizeBy": "none"
          },
          {
            "name": "PY Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f97be94f-a2af-4e41-94dd-0bf4d8a1a8c6",
            "sourceColumn": "PY Volume",
            "summarizeBy": "sum"
          },
          {
            "name": "Transaction Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3a486d3a-d0a3-441b-82c6-93f1928efec1",
            "sourceColumn": "Transaction Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Transaction Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "48a73155-48a0-4f4f-9f35-20217a8d46c2",
            "sourceColumn": "Transaction Volume",
            "summarizeBy": "sum"
          },
          {
            "name": "Value Diff (+)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb7e06d6-5e89-42eb-a668-fbebe6b10f90",
            "sourceColumn": "Value Diff (+)",
            "summarizeBy": "none"
          },
          {
            "name": "Value Diff (-)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adb31f18-fccc-4865-a522-2ba394cf5b1b",
            "sourceColumn": "Value Diff (-)",
            "summarizeBy": "none"
          },
          {
            "name": "Value Diff formatted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6cd716c3-a3de-4e62-97a4-a94978566e4d",
            "sourceColumn": "Value Diff formatted",
            "summarizeBy": "none"
          },
          {
            "name": "Value Diff formatted (-)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b72c35c-795d-42ef-9070-b57091883298",
            "sourceColumn": "Value Diff formatted (-)",
            "summarizeBy": "none"
          },
          {
            "name": "Volume Diff (+)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c7b348e-45f3-449e-a5dd-e2a12f855732",
            "sourceColumn": "Volume Diff (+)",
            "summarizeBy": "none"
          },
          {
            "name": "Volume Diff (-)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d626e5b2-d649-4494-82e9-9d7546f38ee3",
            "sourceColumn": "Volume Diff (-)",
            "summarizeBy": "none"
          },
          {
            "name": "Volume Diff formatted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b015db0-b223-453f-8ead-2675920eec24",
            "sourceColumn": "Volume Diff formatted",
            "summarizeBy": "none"
          },
          {
            "name": "Volume Diff formatted (-)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25920462-781d-475b-b103-a384b2cdec27",
            "sourceColumn": "Volume Diff formatted (-)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b9604ce2-dcf0-4cca-a384-49a6370f1f54",
        "partitions": [
          {
            "name": "transaction_data_transaction_data1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\Data Files\\transaction_data_transaction_data1.csv\"),[Delimiter=\",\", Columns=50, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Channel\", type text}, {\"Flag Reason\", type text}, {\"Is Flagged?\", type text}, {\"Location\", type text}, {\"Months\", type text}, {\"Response Message\", type text}, {\"Transaction Date\", type date}, {\"Transaction Status\", type text}, {\"y/m\", type text}, {\"Year\", Int64.Type}, {\"% MoM success rate (+)\", type text}, {\"% MoM success rate (-)\", type text}, {\"% MoM Value (+)\", type text}, {\"% MoM Value (-)\", type text}, {\"% MoM Volume (+)\", type text}, {\"% MoM Volume (-)\", type text}, {\"% YoY success rate (+)\", type text}, {\"% YoY success rate (-)\", type text}, {\"% YoY Value (+)\", type text}, {\"% YoY Value (-)\", type text}, {\"% YoY Volume (+)\", type text}, {\"% YoY Volume (-)\", type text}, {\"CM Failure Rate\", type text}, {\"CM Flag Transactions\", type text}, {\"CM Success Rate\", type text}, {\"CM Value\", type text}, {\"CM Value formatted\", type text}, {\"CM Volume\", type text}, {\"CY Decline Rate\", type text}, {\"CY Success Rate\", type text}, {\"CY Value\", type text}, {\"CY Volume\", type text}, {\"PM Failure Rate\", type text}, {\"PM Success Rate\", type text}, {\"PM Value\", type text}, {\"PM Volume\", type text}, {\"prev year\", Int64.Type}, {\"PY Success Rate\", Percentage.Type}, {\"PY Value\", type text}, {\"PY Volume\", Int64.Type}, {\"Transaction Value\", type number}, {\"Transaction Volume\", Int64.Type}, {\"Value Diff (+)\", type text}, {\"Value Diff (-)\", type text}, {\"Value Diff formatted\", type text}, {\"Value Diff formatted (-)\", type text}, {\"Volume Diff (+)\", type text}, {\"Volume Diff (-)\", type text}, {\"Volume Diff formatted\", type text}, {\"Volume Diff formatted (-)\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_d864466d-3dc7-4590-bec7-1a3423ef512f",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "044346fe-1ce5-4897-8ded-ac5737836163",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3dfb9cef-f26b-47d7-8ec8-69024980c552",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "215b69a6-d168-44a6-89f6-82c08bf9d752",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "63125424-7f11-4e34-9c6d-50fdbb7f38e9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "41bac216-0e49-47d2-88d2-a92af49c8f21",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c40bfdbc-7433-4584-90ca-2fd464cafb3d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4e97fe6e-1389-4f7a-97e9-f324ce8910b5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "50c2de5f-f4b4-4724-992d-3b6b37866733",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4165f618-8f56-487d-bcca-06a6d0bece94",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d3a175af-41aa-453a-9e10-df6bd5bd0949",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b8101e59-e60c-4b6d-b9a5-9bc3cd24fe93",
                "ordinal": 3
              }
            ],
            "lineageTag": "25bd5705-c726-4f42-831f-8ff22b5a8381"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "bb021b2b-8c2b-46fc-9391-114ed8bd29c9",
        "partitions": [
          {
            "name": "DateTableTemplate_d864466d-3dc7-4590-bec7-1a3423ef512f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_bfdafc33-0205-4ce5-8e87-fb3108f1f953",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "167ec73a-6074-4cc4-a7ed-58ff7f5a3833",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b909321e-03e1-4bf3-a941-a82c2e63c64d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8731c458-811a-45f2-9766-1888267a830c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dd74dc81-7f91-46b7-82e3-4d61b12f7342",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "43f91982-9514-485e-af6a-ad7606c7cc45",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "db88e29c-323a-4320-86f5-9a9497268b0b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2f339205-dde7-45a9-a5d2-25ec788bd729",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a0163ca0-1a58-430f-a067-22c3e8b478b3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "42046b3e-5acc-4f4c-b089-42404fcaf51a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2dfadb67-4a01-4b60-99f3-9b5ee15db28a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5927510f-8e93-45dc-bde4-bbf7f10aa9e5",
                "ordinal": 3
              }
            ],
            "lineageTag": "cf805eb2-7077-4db3-ae40-e41ff7a00bfa"
          }
        ],
        "isHidden": true,
        "lineageTag": "bd3b291c-41ba-4a51-8290-1e3295d08646",
        "partitions": [
          {
            "name": "LocalDateTable_bfdafc33-0205-4ce5-8e87-fb3108f1f953",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('transaction_data_transaction_data1'[Transaction Date])), 1, 1), Date(Year(MAX('transaction_data_transaction_data1'[Transaction Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}